/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    sites: Site;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    'contact-submissions': ContactSubmission;
    'newsletter-submissions': NewsletterSubmission;
    'sindicalize-submissions': SindicalizeSubmission;
    'sindicato-page': SindicatoPage;
    'juridico-page': JuridicoPage;
    'servicos-page': ServicosPage;
    'cta-sections': CtaSection;
    'announcement-cards': AnnouncementCard;
    redirects: Redirect;
    search: Search;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    sites: SitesSelect<false> | SitesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'newsletter-submissions': NewsletterSubmissionsSelect<false> | NewsletterSubmissionsSelect<true>;
    'sindicalize-submissions': SindicalizeSubmissionsSelect<false> | SindicalizeSubmissionsSelect<true>;
    'sindicato-page': SindicatoPageSelect<false> | SindicatoPageSelect<true>;
    'juridico-page': JuridicoPageSelect<false> | JuridicoPageSelect<true>;
    'servicos-page': ServicosPageSelect<false> | ServicosPageSelect<true>;
    'cta-sections': CtaSectionsSelect<false> | CtaSectionsSelect<true>;
    'announcement-cards': AnnouncementCardsSelect<false> | AnnouncementCardsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  name: string;
  url: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * URL para invalidação de cache do frontend
   */
  webhookUrl?: string | null;
  /**
   * Token secreto para autenticação
   */
  webhookSecret?: string | null;
  contact?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    /**
     * Opcional
     */
    whatsapp?: string | null;
    workingHours?: string | null;
  };
  header?: {
    logo?: (number | null) | Media;
    logoAlt?: string | null;
    navItems?:
      | {
          label: string;
          href: string;
          /**
           * Renderizar como botão no frontend
           */
          isButton?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  footer?: {
    logo?: (number | null) | Media;
    /**
     * Texto sobre o sindicato que aparece no footer
     */
    description?: string | null;
    socialLinks?: {
      facebook?: string | null;
      instagram?: string | null;
      twitter?: string | null;
      youtube?: string | null;
    };
  };
  /**
   * Imagens do carrossel da homepage. Se vazio, o hero estático será exibido.
   */
  slides?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Hero estático (fallback caso o carrossel esteja vazio)
   */
  hero?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    imageAlt?: string | null;
    primaryButtonText?: string | null;
    primaryButtonHref?: string | null;
    secondaryButtonText?: string | null;
    secondaryButtonHref?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  sites: (number | Site)[];
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * URL amigável gerada automaticamente
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  nome: string;
  email: string;
  /**
   * Formato: (00) 00000-0000
   */
  telefone: string;
  assunto: string;
  mensagem: string;
  site: number | Site;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-submissions".
 */
export interface NewsletterSubmission {
  id: number;
  nomeCompleto: string;
  email: string;
  /**
   * Formato: (00) 00000-0000
   */
  celular: string;
  newsletterAccepted: boolean;
  site: number | Site;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sindicalize-submissions".
 */
export interface SindicalizeSubmission {
  id: number;
  nomeCompleto: string;
  /**
   * Formato: 000.000.000-00
   */
  cpf: string;
  email: string;
  /**
   * Formato: (00) 00000-0000
   */
  celular: string;
  dataNascimento: string;
  empresaVeiculo: string;
  cargoFuncao: string;
  /**
   * Imagem da assinatura em base64
   */
  assinaturaDigital: string;
  declaracaoLida: boolean;
  site: number | Site;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sindicato-page".
 */
export interface SindicatoPage {
  id: number;
  locationsSection: {
    badge?: string | null;
    title: string;
    description?: string | null;
    /**
     * URL de incorporação do Google Maps
     */
    mapEmbedUrl?: string | null;
    locations?:
      | {
          title: string;
          description?: string | null;
          address?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          mapUrl?: string | null;
          icon?: ('map-pin' | 'building' | 'office') | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Adicione seções como Diretoria Executiva, Conselho Fiscal, etc.
   */
  teamSections?:
    | {
        id: string;
        title: string;
        badge?: string | null;
        description?: string | null;
        members?:
          | {
              id: string;
              name: string;
              role: string;
              image?: (number | null) | Media;
              imageAlt?: string | null;
            }[]
          | null;
      }[]
    | null;
  /**
   * Cada site pode ter apenas uma página de Sindicato
   */
  site: number | Site;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "juridico-page".
 */
export interface JuridicoPage {
  id: number;
  contactInfo: {
    badge?: string | null;
    title: string;
    description?: string | null;
    contacts?:
      | {
          icon: 'mail' | 'map-pin' | 'phone';
          title: string;
          description?: string | null;
          linkText: string;
          linkHref: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Abas: Atendimento, Plantão Jurídico, Escritórios Conveniados, Homologação, Consulta Processual, Ações Coletivas
   */
  tabs?:
    | {
        id: string;
        label: string;
        badge?: string | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
      }[]
    | null;
  /**
   * Cada site pode ter apenas uma página Jurídico
   */
  site: number | Site;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicos-page".
 */
export interface ServicosPage {
  id: number;
  hero: {
    badge?: string | null;
    title: string;
    description?: string | null;
    image?: (number | null) | Media;
    imageAlt?: string | null;
    features?:
      | {
          icon?: string | null;
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  benefits: {
    badge?: string | null;
    title: string;
    subtitle?: string | null;
    categories?:
      | {
          id: string;
          name: string;
          benefits?:
            | {
                name: string;
                discount?: string | null;
                address?: string | null;
                phone?: string | null;
                hours?: string | null;
                observations?: string | null;
                id?: string | null;
              }[]
            | null;
        }[]
      | null;
  };
  /**
   * Ex: Alojamento para Radialistas, Ginásio, etc.
   */
  facilities?:
    | {
        badge?: string | null;
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        imageAlt?: string | null;
        priceTable?:
          | {
              description: string;
              price: string;
              id?: string | null;
            }[]
          | null;
        generalInfo?:
          | {
              info: string;
              id?: string | null;
            }[]
          | null;
        contactInfo?: {
          hours?: string | null;
          email?: string | null;
          phone?: string | null;
        };
        regulations?:
          | {
              rule: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Cada site pode ter apenas uma página de Serviços
   */
  site: number | Site;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-sections".
 */
export interface CtaSection {
  id: number;
  page: 'sindicato' | 'juridico' | 'servicos';
  title: string;
  description?: string | null;
  primaryButtonText?: string | null;
  primaryButtonHref?: string | null;
  secondaryButtonText?: string | null;
  secondaryButtonHref?: string | null;
  image?: (number | null) | Media;
  imageAlt?: string | null;
  site: number | Site;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement-cards".
 */
export interface AnnouncementCard {
  id: number;
  page: 'sindicato' | 'juridico' | 'servicos';
  title: string;
  description?: string | null;
  primaryButtonText?: string | null;
  primaryButtonHref?: string | null;
  image?: (number | null) | Media;
  imageAlt?: string | null;
  site: number | Site;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Você precisará reconstruir o site ao alterar este campo.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'newsletter-submissions';
        value: number | NewsletterSubmission;
      } | null)
    | ({
        relationTo: 'sindicalize-submissions';
        value: number | SindicalizeSubmission;
      } | null)
    | ({
        relationTo: 'sindicato-page';
        value: number | SindicatoPage;
      } | null)
    | ({
        relationTo: 'juridico-page';
        value: number | JuridicoPage;
      } | null)
    | ({
        relationTo: 'servicos-page';
        value: number | ServicosPage;
      } | null)
    | ({
        relationTo: 'cta-sections';
        value: number | CtaSection;
      } | null)
    | ({
        relationTo: 'announcement-cards';
        value: number | AnnouncementCard;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  url?: T;
  generateSlug?: T;
  slug?: T;
  webhookUrl?: T;
  webhookSecret?: T;
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
        whatsapp?: T;
        workingHours?: T;
      };
  header?:
    | T
    | {
        logo?: T;
        logoAlt?: T;
        navItems?:
          | T
          | {
              label?: T;
              href?: T;
              isButton?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        logo?: T;
        description?: T;
        socialLinks?:
          | T
          | {
              facebook?: T;
              instagram?: T;
              twitter?: T;
              youtube?: T;
            };
      };
  slides?:
    | T
    | {
        image?: T;
        id?: T;
      };
  hero?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        primaryButtonText?: T;
        primaryButtonHref?: T;
        secondaryButtonText?: T;
        secondaryButtonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  sites?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  nome?: T;
  email?: T;
  telefone?: T;
  assunto?: T;
  mensagem?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-submissions_select".
 */
export interface NewsletterSubmissionsSelect<T extends boolean = true> {
  nomeCompleto?: T;
  email?: T;
  celular?: T;
  newsletterAccepted?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sindicalize-submissions_select".
 */
export interface SindicalizeSubmissionsSelect<T extends boolean = true> {
  nomeCompleto?: T;
  cpf?: T;
  email?: T;
  celular?: T;
  dataNascimento?: T;
  empresaVeiculo?: T;
  cargoFuncao?: T;
  assinaturaDigital?: T;
  declaracaoLida?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sindicato-page_select".
 */
export interface SindicatoPageSelect<T extends boolean = true> {
  locationsSection?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        mapEmbedUrl?: T;
        locations?:
          | T
          | {
              title?: T;
              description?: T;
              address?: T;
              mapUrl?: T;
              icon?: T;
              id?: T;
            };
      };
  teamSections?:
    | T
    | {
        id?: T;
        title?: T;
        badge?: T;
        description?: T;
        members?:
          | T
          | {
              id?: T;
              name?: T;
              role?: T;
              image?: T;
              imageAlt?: T;
            };
      };
  site?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "juridico-page_select".
 */
export interface JuridicoPageSelect<T extends boolean = true> {
  contactInfo?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        contacts?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              linkText?: T;
              linkHref?: T;
              id?: T;
            };
      };
  tabs?:
    | T
    | {
        id?: T;
        label?: T;
        badge?: T;
        content?: T;
      };
  site?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicos-page_select".
 */
export interface ServicosPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        features?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  benefits?:
    | T
    | {
        badge?: T;
        title?: T;
        subtitle?: T;
        categories?:
          | T
          | {
              id?: T;
              name?: T;
              benefits?:
                | T
                | {
                    name?: T;
                    discount?: T;
                    address?: T;
                    phone?: T;
                    hours?: T;
                    observations?: T;
                    id?: T;
                  };
            };
      };
  facilities?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        priceTable?:
          | T
          | {
              description?: T;
              price?: T;
              id?: T;
            };
        generalInfo?:
          | T
          | {
              info?: T;
              id?: T;
            };
        contactInfo?:
          | T
          | {
              hours?: T;
              email?: T;
              phone?: T;
            };
        regulations?:
          | T
          | {
              rule?: T;
              id?: T;
            };
        id?: T;
      };
  site?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-sections_select".
 */
export interface CtaSectionsSelect<T extends boolean = true> {
  page?: T;
  title?: T;
  description?: T;
  primaryButtonText?: T;
  primaryButtonHref?: T;
  secondaryButtonText?: T;
  secondaryButtonHref?: T;
  image?: T;
  imageAlt?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement-cards_select".
 */
export interface AnnouncementCardsSelect<T extends boolean = true> {
  page?: T;
  title?: T;
  description?: T;
  primaryButtonText?: T;
  primaryButtonHref?: T;
  image?: T;
  imageAlt?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}